# Generated by Django 3.1.2 on 2020-10-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='UsersList',
        ),
    ]
